#!/bin/bash
#PBS -N matrix-free-PDE
#PBS -q cpu
#PBS -l select=1:ncpus=28:mem=96gb
#PBS -l walltime=02:30:00
#PBS -j oe

cd $PBS_O_WORKDIR

echo "Starting polynomial scaling job..."

rm ./matrix-free/out/poly.out
rm ./matrix-based/out/poly.out

mpirun -np 32 ./matrix-free/build/matrix_free &>> ./matrix-free/out/poly.out
mpirun -np 32 ./matrix-based/build/matrix_based &>> ./matrix-based/out/poly.out

echo >> ./matrix-free/out/poly.out
echo >> ./matrix-free/out/poly.out

echo >> ./matrix-based/out/poly.out
echo >> ./matrix-based/out/poly.out

echo "Polynomial scaling job finished!"