#!/bin/bash
#PBS -N weak-scaling-PDE
#PBS -q cpu
#PBS -l select=1:ncpus=28:mem=96gb
#PBS -l walltime=02:30:00
#PBS -j oe

cd $PBS_O_WORKDIR

echo "Starting weak scaling job..."

rm ./matrix-free/out/weak.out
rm ./matrix-based/out/weak.out

mpirun -np 1 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 1 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 2 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 2 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 4 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 4 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 8 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 8 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 16 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 16 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 32 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 32 ./matrix-free/build/matrix_free &>> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out
echo >> ./matrix-free/out/weak.out

mpirun -np 1 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 1 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 2 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 2 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 4 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 4 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 8 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 8 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 16 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 16 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 32 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

mpirun -np 32 ./matrix-based/build/matrix_based &>> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out
echo >> ./matrix-based/out/weak.out

echo "Weak scaling job finished!"